package th.ac.cmu.cpe.cpe406.frontend;

/**
 * Interface for defining source files
 */
public interface Source {
    static enum Kind {
        /** Indicates the source file was specified by the user. */
        USER_SPECIFIED,

        /** Indicates the source file was pulled in as a dependency. */
        DEPENDENCY,

        /** Indicates the source file was generated by the compiler. */
        COMPILER_GENERATED
    }

    boolean userSpecified();

    boolean compilerGenerated();

    void setKind(Kind kind);

    Kind kind();

    String name();

    String path();
}
